### ISSUE TITLE
return 401 when no authorization header is found instead of 500

### ISSUE THREAD

**Issue by jfromaniello** [auth0/express-jwt#1]

**Comment by yash-sharma9091** [comment]
Is it possible to handle 404 routes using `expressJWT` middleware, basically i have a mean app so if user hit a route without '#' it will goes to express server and `expressJWT` middleware triigers and 401 `Unauthorised error`.
please suggest

**Comment by aadi3124** [comment]
hi,
I am quite new in nodejs and express, getting this error and not finding any solution. Please help me.
thanks!

C:\D\PlayBox\back_end\middlewares\auth.js:41
    return res.sendStatus(401).send("Invalid Token");
               ^

TypeError: Cannot read properties of undefined (reading 'sendStatus')
    at Object.verifyToken (C:\D\PlayBox\back_end\middlewares\auth.js:41:16)
    at C:\D\PlayBox\back_end\app.js:70:21
    at Layer.handle [as handle_request] (C:\D\PlayBox\back_end\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\D\PlayBox\back_end\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\D\PlayBox\back_end\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\D\PlayBox\back_end\node_modules\express\lib\router\layer.js:95:5)
    at C:\D\PlayBox\back_end\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\D\PlayBox\back_end\node_modules\express\lib\router\index.js:341:12)
    at next (C:\D\PlayBox\back_end\node_modules\express\lib\router\index.js:275:10)
    at jsonParser (C:\D\PlayBox\back_end\node_modules\body-parser\lib\types\json.js:119:7)
[nodemon] app crashed - waiting for file changes before starting...



#This is my code#

`function verifyToken(req, res, next) {
  let token = req.body.token || req.query.token || req.headers["authorization"];
  token = token.split(" ")[1];

  console.log(">>>>>token   " + token);
  if (!token) {
    return res.send(403, "A token is required for authentication");
  }
  try {
    const decoded = jwt.verify(token, "process.env.ACCESS_TOKEN_SECRET");
    req.user = decoded;
  } catch (err) {
    return res.sendStatus(401).send("Invalid Token");
  }
  return next();
}`


getting error in this line >>>  return res.sendStatus(401).send("Invalid Token");

**Comment by ugurberkecan** [comment]
@aadi3124 did u find a solution for it ?
