### ISSUE TITLE
Error with router

### ISSUE THREAD

**Issue by jerome724** [auth0/express-jwt#151]
```js
	router.get('/test', jwt({
		secret: 'test'
	}), (req, res ) => {
		if(!req.user.admin) return res.status(401);
		res.status(200);
	})
```

is my route, when i try to access the route i get this error:

```js
Error
   at middleware (C:\Users\jerom\Git\web\node_modules\express-jwt\lib\index.js:75:21)
   at Layer.handle [as handle_request] (C:\Users\jerom\Git\web\node_modules\express\lib\router\layer.js:95:5)
   at next (C:\Users\jerom\Git\web\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (C:\Users\jerom\Git\web\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (C:\Users\jerom\Git\web\node_modules\express\lib\router\layer.js:95:5)
   at C:\Users\jerom\Git\web\node_modules\express\lib\router\index.js:277:22
   at Function.process_params (C:\Users\jerom\Git\web\node_modules\express\lib\router\index.js:330:12)
   at next (C:\Users\jerom\Git\web\node_modules\express\lib\router\index.js:271:10)
   at router.use (C:\Users\jerom\Git\web\routes\api.js:19:3)
   at Layer.handle [as handle_request] (C:\Users\jerom\Git\web\node_modules\express\lib\router\layer.js:95:5)
```

can't figure out why i'm getting this error. Is this a known issue with the express router?

**Comment by jerome724** [comment]
nvm, my bad.

**Comment by fuxes** [comment]
@jerome724 could you please share what was your problem? I'm having the same issue.

**Comment by davidfarinha** [comment]
Me too, what was the issue in the end?

**Comment by bitliner** [comment]
What is the issue? I continue to get this issue inconsistently/randomly

**Comment by andregs** [comment]
I'm not using nvm but I'm also facing this issue.

**Comment by sylentmode** [comment]
I ran into the issue and digging in...it looks like this is as designed. The best _workaround_ I see is to add this to the bottom of your express app before opening the port

```
app.use(function (err, req, res, next) {
  if (err.name === 'UnauthorizedError') {
    res.status(401).send(err.inner);
  }
});
```
this should provide a clearer error message

**Comment by jelling** [comment]
To summarize what's happening here, by default express-jwt is throwing a proper 401 error. The information about the error is implicit in the header being set to a 401, which means unauthorized. But if you're looking at the error in the console or POSTMAN, you just see the not-so-clear "Error in middleware" message.

@sylentmode's code makes the text of the error more clear. Thanks for the code.
