### ISSUE TITLE
Getting annoying logging with stacktrace.

### ISSUE THREAD

**Issue by Levino** [auth0/express-jwt#159]
If I send a request without any authorization token, express logs an error to the console.

```
UnauthorizedError: No authorization token was found
    at middleware (/home/levin/coding/satoshipay/nano-btc-vendor/server/node_modules/express-jwt/lib/index.js:75:21)
    at Layer.handle [as handle_request] (/home/levin/coding/satoshipay/nano-btc-vendor/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/levin/coding/satoshipay/nano-btc-vendor/server/node_modules/express/lib/router/index.js:312:13)
    at /home/levin/coding/satoshipay/nano-btc-vendor/server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/levin/coding/satoshipay/nano-btc-vendor/server/node_modules/express/lib/router/index.js:330:12)
    at next (/home/levin/coding/satoshipay/nano-btc-vendor/server/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/home/levin/coding/satoshipay/nano-btc-vendor/server/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/home/levin/coding/satoshipay/nano-btc-vendor/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/levin/coding/satoshipay/nano-btc-vendor/server/node_modules/express/lib/router/index.js:312:13)
    at /home/levin/coding/satoshipay/nano-btc-vendor/server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/levin/coding/satoshipay/nano-btc-vendor/server/node_modules/express/lib/router/index.js:330:12)
    at next (/home/levin/coding/satoshipay/nano-btc-vendor/server/node_modules/express/lib/router/index.js:271:10)
    at query (/home/levin/coding/satoshipay/nano-btc-vendor/server/node_modules/express/lib/middleware/query.js:44:5)
    at Layer.handle [as handle_request] (/home/levin/coding/satoshipay/nano-btc-vendor/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/levin/coding/satoshipay/nano-btc-vendor/server/node_modules/express/lib/router/index.js:312:13)
    at /home/levin/coding/satoshipay/nano-btc-vendor/server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/levin/coding/satoshipay/nano-btc-vendor/server/node_modules/express/lib/router/index.js:330:12)
    at next (/home/levin/coding/satoshipay/nano-btc-vendor/server/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/home/levin/coding/satoshipay/nano-btc-vendor/server/node_modules/express/lib/router/index.js:176:3)
    at EventEmitter.handle (/home/levin/coding/satoshipay/nano-btc-vendor/server/node_modules/express/lib/application.js:173:10)
    at Server.app (/home/levin/coding/satoshipay/nano-btc-vendor/server/node_modules/express/lib/express.js:38:9)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```

The error itself is fine for me, I handle it in an appropiate middleware, but I do NOT want this stacktrace to be logged. I cannot find where to switch it off or which package is actually logging this stuff. I am also using ```express-jwt-authz``` and ```express-jwt-permissions```

**Comment by Ryuji13** [comment]
Hello, I see that your stack trace is displaying correctly the error "No authorization token was found".

Have you changed some code to make it work ? In my project, the stack trace only display "Error" at the beginning and not precisely the cause of the error.

Concerning your question, i think the stack trace won't show up anymore if you set NODE_ENV value to production.

**Comment by Levino** [comment]
No I have not changed the code of this package to make this logging work. Actually I could not figure out why it being logged.

I expect this not to be logged. Also not when in "development". I have a test that is expected to fail: I query the endpoint without and authentication token and want a 401 or 404. I consider this NOT AN ERROR. Someone has no credentials, my server tells him go get lost. This is expected behaviour. It is very annoying to have these "error dumps" in my logs when I run my test suite.

**Comment by Ryuji13** [comment]
I know where is located the code which is writing that strack trace.
You cand find it in the UnauthorizedError.js file in your express-jwt node module.
I don't know how to avoid the stack trace to be written with configuration but you can define your own UnauthorizedError function which won't call the captureStackTrace function.
Howerver, I think there's a better way to do this.

**Comment by Levino** [comment]
Can you please link the line in the file?

**Comment by Ryuji13** [comment]
Error.captureStackTrace(this, this.constructor);

**Comment by Levino** [comment]
https://github.com/auth0/express-jwt/blob/master/lib/errors/UnauthorizedError.js#L3

I don't think that this logs the error. It merely adds it to the error object. See also the Node [docs](https://nodejs.org/api/errors.html#errors_error_capturestacktrace_targetobject_constructoropt)

> Creates a .stack property on targetObject, which when accessed returns a string representing the location in the code at which Error.captureStackTrace() was called.

**Comment by Ryuji13** [comment]
You can try it by commenting this line.

**Comment by jmmorlesin** [comment]
I can understand print the errors, but when you are using a /login is normal not pass the authorization token, because you want to login and get this token. For that reason, I don't think we need print the 'UnauthorizedError: No authorization token was found' on login.

In my case, I'm using 

app.use(expressJWT({secret: SECRET}).unless({path:['/login']}));

**Comment by jmmorlesin** [comment]
I did some tests and analysing the module of unless, it seems the solution it was easier, so add '/favicon.ico' to the path, because in the browser, the behaviour is the expected, but it is when it tries to get the favicon when the message is showed on console.

So 
app.use(expressJWT({secret: SECRET}).unless({path:['/login', '/favicon.ico']}));
fix the problem to me

**Comment by enricop89** [comment]
@Levino Did you solve it? Are you able to avoid the stacktrace? It is very annoying.

**Comment by Levino** [comment]
No I did not have time to look into it yet, sorry.

**Comment by ZaphodBBX** [comment]
does running the app with NODE_ENV=production help?

**Comment by enricop89** [comment]
No, running in production doesn't help

**Comment by tocttou** [comment]
I am facing the same issue. Any fix?

**Comment by jfromaniello** [comment]
This library does `next(err)` it doesnt log the error itself. You might have a error logger middleware which is the same than a normal middleware but with an additional parameter `app.use(function(err, req, res, next)` or maybe this is the default behavior of express when you dont have any. Please show us all the middlewares you are adding to express, maybe we can help

**Comment by jfromaniello** [comment]
Please read vert carefully this document, you will find this extremely helpful not only for this middleware but for all others:

http://expressjs.com/en/guide/error-handling.html

**Comment by tocttou** [comment]
I got it. Thanks!

**Comment by Levino** [comment]
So I made a very [simple test to reproduce](https://github.com/Levino/express-jwt/commit/51d2bed490d68ed027794734e7423fd619e05acd) the issue and made the easiest example I could think of. Maybe I am doing something wrong, then please help me figuring out what it is.

When I run the tests, I get this output:

```
> express-jwt@5.3.0 test /home/levin/coding/levino/express-jwt
> mocha --reporter spec

(node:18745) [DEP0006] DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.


  Testing the middleware in an express app
    ✓ should not log errors when not token present 
UnauthorizedError: No authorization token was found
    at middleware (/home/levin/coding/levino/express-jwt/lib/index.js:76:21)
    at Layer.handle [as handle_request] (/home/levin/coding/levino/express-jwt/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/levin/coding/levino/express-jwt/node_modules/express/lib/router/index.js:317:13)
    at /home/levin/coding/levino/express-jwt/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/levin/coding/levino/express-jwt/node_modules/express/lib/router/index.js:335:12)
    at next (/home/levin/coding/levino/express-jwt/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/home/levin/coding/levino/express-jwt/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/home/levin/coding/levino/express-jwt/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/levin/coding/levino/express-jwt/node_modules/express/lib/router/index.js:317:13)
    at /home/levin/coding/levino/express-jwt/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/levin/coding/levino/express-jwt/node_modules/express/lib/router/index.js:335:12)
    at next (/home/levin/coding/levino/express-jwt/node_modules/express/lib/router/index.js:275:10)
    at query (/home/levin/coding/levino/express-jwt/node_modules/express/lib/middleware/query.js:44:5)
    at Layer.handle [as handle_request] (/home/levin/coding/levino/express-jwt/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/levin/coding/levino/express-jwt/node_modules/express/lib/router/index.js:317:13)
    at /home/levin/coding/levino/express-jwt/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/levin/coding/levino/express-jwt/node_modules/express/lib/router/index.js:335:12)
    at next (/home/levin/coding/levino/express-jwt/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/levin/coding/levino/express-jwt/node_modules/express/lib/router/index.js:174:3)
    at Function.handle (/home/levin/coding/levino/express-jwt/node_modules/express/lib/application.js:174:10)
    at Server.app (/home/levin/coding/levino/express-jwt/node_modules/express/lib/express.js:38:9)
    at emitTwo (events.js:125:13)
    at Server.emit (events.js:213:7)
    at parserOnIncoming (_http_server.js:602:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)


  1 passing (37ms)
```

**Comment by jfromaniello** [comment]
@Levino you didn't read my message here and you didn't read the README file of the project. Again:

1. There is no console.log or anything like that in this project.
2. This is the default behavior of express.js.
3. If you want to change this default behavior, please follow the instructions on the readme: https://github.com/auth0/express-jwt#error-handling

For instance change your test to this:

```javascript
const middleware = expressJwt({secret: 'geheim'})
app.use(middleware)
app.use(function (err, req, res, next) {
  if (err.name === 'UnauthorizedError') {
    res.status(401).send('invalid token');
  } else {
    next(err);
  }
});
return request(app).get('/').expect(401)
```

**Comment by Levino** [comment]
Thank you @jfromaniello for following up. So what you are referring to is [this part](https://github.com/auth0/express-jwt#error-handling) of the Readme or more specifically:

> The default behavior is to throw an error when the token is invalid, so you can add your custom logic to manage unauthorized access as follows:

Which I understand. However what totally confuses me is that even though an error is thrown, still an answer is sent back with a status of 401. I would either expect an error to be thrown and if I do not handle that error the app should crash. Or if the middleware sends a reply, then no error is thrown. I do not get this double approach and would really appreciate some further explanation on this.

**Comment by Levino** [comment]
Okay. I read a little more and turns out I did not know about the "Default Error handler" of express which dumps the stacktrace to the console and sends it to the client. See also here at the bottom http://expressjs.com/en/guide/error-handling.html (as @jfromaniello suggested).

I still find it weird to throw an actual error when the authorization fails (I think "denying access when no token is present, eg sending a 401" is a user story - so to say a success of the middleware - and not an exception) but I can live with it.

So this can be the baseline of the whole issue:

This middleware throws errors when no token is present. These errors should be handled by a middleware to avoid handling of these errors by the express default error handler which logs the stacktrace it to the console.

I think it would be nice if the middleware was configurable in the sense that I can tell it to just send 401s on missing or invalid tokens instead of throwing errors. Right now I have to write an error handling middleware as you suggested [above](https://github.com/auth0/express-jwt/issues/159#issuecomment-318297379) which is imo bad practice because in the middleware I have to check "from which middleware" the error is coming from, which should be abstracted away.

**Comment by Levino** [comment]
One final thought: An attacker could send lots of requests without a token. Would the throwing of an error not create a certain overhead over just returning a 401 without throwing and as such amplify the attack? I know that in Java throwing an error is expensive and should not be done for "expected use cases". Is this diffferent in NodeJS / Javascript?

**Comment by jfromaniello** [comment]
One more information bit that can help understand how the default handler works. IF the error object has an `status` property it uses that for the status of the response.

https://github.com/auth0/express-jwt/blob/9ff413a6350ad0117ddef82e9da7eaeb55061e0b/lib/errors/UnauthorizedError.js#L7

Whats the API you are expecting?

**Comment by Levino** [comment]
Maybe something like this could work:

```js
var jwt = require('express-jwt');

app.get('/protected',
  jwt({
     secret: 'shhhhhhared-secret',
     errorOnFailedAuth: false
  }),
  function(req, res) {
    res.sendStatus(200);
  });
```

Where `errorOnFailedAuth` defaults to `true`. Setting it to `false` would make the middleware just send back 401s and a standard message like: "Authorization token missing" or "Authorization token invalid". All other cases should still produce an error.

It still feels a little clunky, but I understand of course the need to be able to handle the event "Authorization token missing" (and others) in a more customized manner.

**Comment by cif** [comment]
Stack traces are definitely a security liability. Search for easy way to suppress landed me here.  `app.use(fn)` chaining method used in docs which @jfromaniello references above didn't work for me using `express@4.16.2` 

However, when I ended up using middleware functions as arguments to `app.get()` it works as I was hoping for:

```js
const HTTP_UNAUTHORIZED = 401
const handleUnauthorizedError = (err, req, res, next) => {
  if (err.status == HTTP_UNAUTHORIZED) {
    return res.status(HTTP_UNAUTHORIZED).send('Unauthrorized')
  }
  next()
}
app.get(
  '/secure-endpoint',
  jwt({ secret: JWT_SECRET }),
  handleUnauthorizedError,
  (req, res) => {
    // do the things
  }
)
```


Hope that helps someone else. If maintainers like, I would be happy to submit a quick PR to update to docs with the suggestion ✌️

**Comment by GAumala** [comment]
If `app.use` doesn't work fix issue for you, make sure you are calling it **at the end**. From [express's documentation](http://expressjs.com/en/guide/error-handling.html#writing-error-handlers):

> You define error-handling middleware last, after other app.use() and routes calls;

**Comment by Levino** [comment]
Closing because I can and this is not an unresolved problem.
