### ISSUE TITLE
Private Key Signing not verifying Public key

### ISSUE THREAD

**Issue by Ankiewicz** [auth0/express-jwt#162]
Losing my mind over this. I am following your instructions in the read me. System works great with a general secret key. So I am trying to take it to the next level and use a public and private key secrets. I keep receiving:

```
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Sign.sign (crypto.js:285:26)
    at Object.sign (/Users/Jonathan/foundation/simplefi_auth/node_modules/jwa/index.js:55:45)
    at Object.jwsSign [as sign] (/Users/Jonathan/foundation/simplefi_auth/node_modules/jws/lib/sign-stream.js:23:24)
    at Object.module.exports [as sign] (/Users/Jonathan/foundation/simplefi_auth/node_modules/jsonwebtoken/sign.js:146:16)
    at /Users/Jonathan/foundation/simplefi_auth/routes/server.js:19:23
    at Layer.handle [as handle_request] (/Users/Jonathan/foundation/simplefi_auth/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/Jonathan/foundation/simplefi_auth/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/Jonathan/foundation/simplefi_auth/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/Jonathan/foundation/simplefi_auth/node_modules/express/lib/router/layer.js:95:5)
    at /Users/Jonathan/foundation/simplefi_auth/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/Jonathan/foundation/simplefi_auth/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/Jonathan/foundation/simplefi_auth/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/Jonathan/foundation/simplefi_auth/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/Jonathan/foundation/simplefi_auth/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/Jonathan/foundation/simplefi_auth/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/Jonathan/foundation/simplefi_auth/node_modules/express/lib/router/index.js:317:13)

```

Creating the token and storing as a token
```              
  let myToken = jwt.sign({
                    username: req.body.username,
                    user_id: user._id,
                }, secretToken, {
                    algorithm: 'RS256'
                })
                res.cookie('token', myToken)
                res.redirect(302, '/getUser')

```

Verifying Middleware 
```
// Authorization middleware
app.use(expressJwt({
        secret: secretToken,
        credentialsRequired: false,
        getToken: function fromHeaderOrQuerystring(req) {
            // console.log('req.cookies - ', req.name)
            if (req.headers.authorization && req.headers.authorization.split(' ')[0] === 'Bearer') {
                return req.headers.authorization.split(' ')[1]
            } else if (req.cookies && req.cookies.token) {
                // console.log('req.cookies - ', req.cookies)
                return req.cookies.token
            }
            return null
        }
    })
    // allows pages to be landed out without require AUTH
    .unless({
        path: ['/login', '/createUser', '/']
    }))
```

building rsa keys with - http://travistidwell.com/jsencrypt/demo/

**Comment by jfromaniello** [comment]
The error message looks like a problem with your keys and the error is being thrown in the signing library. My guess is that you had a problem copy pasting the certificate

You shouldn't be generating a certificate in a third party website, use openssl instead like this:

```
openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout server.key -out server.crt
```

**Comment by Ankiewicz** [comment]
looking to generate keys this way and testing it

**Comment by Ankiewicz** [comment]
Could someone point me to a working sample of RSA public and private key using this package?

**Comment by jfromaniello** [comment]
Since your issue is signing the token with the jsonwebtoken module:

https://github.com/auth0/node-jsonwebtoken/blob/master/test/jwt.rs.tests.js

**Comment by Ankiewicz** [comment]
OMG, I LOVE YOU(no homo)... 

Seriously you are a life saver, it only took me several hours. but I have a finally have a full auth token system using public and private keys.... Thank you!

I hope my notations below can be added to read me instructions or at the least left here to so that this might help some other poor soul.

Required Packages:
```
import jwt from 'jsonwebtoken'
import expressJwt from 'express-jwt'
```

Create below RSA key Command

```
openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout server.key -out server.crt
```
Creates a server.crt and server.key
server.crt = public key
server.key = private key

Route for creating a user and setting a JWT token

```
var secretTokenPriv = fs.readFileSync('server.key')  // get private key
```


```
// Creating a new user
router.post('/createUser', (req, res, next) => {
    let newUser = new User({
        username: req.body.username,
        password: req.body.password,
    })
    
    let myToken = jwt.sign({
        username: req.body.username
    }, secretTokenPriv, {
         algorithm: 'RS256',
         issuer: 'urn:issuer'
    })
    
    User.createUser(newUser)
    // sets cookie/jwt for validation
    res.cookie('token', myToken).redirect(302, '/getUser')
}) // end of createUser Put
```




MiddleWare to verify User
```
let secretTokenPub = fs.readFileSync('server.crt')
```

```
app.use(expressJwt({
        secret: secretTokenPub,
        getToken: function fromHeaderOrQuerystring(req) {
            if (req.headers.authorization && req.headers.authorization.split(' ')[0] === 'Bearer') {
                return req.headers.authorization.split(' ')[1]
            } else if (req.cookies && req.cookies.token) {
                // console.log('req.cookies - ', req.cookies)
              return req.cookies.token
            }
            return null
        }
    })
    // allows pages to be landed out without require AUTH
    .unless({
        path: ['/login', '/createUser', '/']
    }))
```
