### ISSUE TITLE
`UnauthorizedError: jwt expired` being thrown with `credentialsRequired: false`

### ISSUE THREAD

**Issue by lorensr** [auth0/express-jwt#194]
I believe that according to https://github.com/auth0/express-jwt/pull/47 I should not get this error?

```
UnauthorizedError: jwt expired
    at /Users/me/gh/api-model/node_modules/express-jwt/lib/index.js:102:22
    at /Users/me/gh/api-model/node_modules/jsonwebtoken/verify.js:27:18
```

Code:

```js
import jwt from 'express-jwt'

expressApp.use(
  '/graphql',
  jwt({
    ...
    credentialsRequired: false
  }),
  ...
)
```

Version: `"express-jwt": "^5.3.0",`

**Comment by Vanthiyadevan** [comment]
Having a same problem to me unable use the custom error handling

**Comment by Vanthiyadevan** [comment]
Ok this problem is solved for me if i put the credentials required: false as a first option parameter.

```
expressJwt({
	credentialsRequired: false,
	secret: config.secrets,
	getToken: function (req) {
		if (req.headers.authorization && req.headers.authorization.split(' ')[0] === 'Bearer') {
			return req.headers.authorization.split(' ')[1];
                 }
		return null;
	  }
});
```

**Comment by SimonStiph** [comment]
@Vanthiyadevan that didn't work for me, and I don't think that the order of parameters should matter in any reasonable context.

This issue is pretty straightforward: In most circumstances, it's logically disjointed to allow the forward sequence of a request without credentials, yet deny a request that has expired credentials. 

Therefore an option to allow the forward sequence of a request with expired credentials should be included; that has the added benefit of not breaking any apps that might now rely on the current behavior.

**Comment by Vanthiyadevan** [comment]
@SimonStiph I was wrong i forgot to update this comment. I was looking in to the code in lib/index.js. They call a `next(err)` or `next(data)` what ever happens. Basically ut calls the nodejs default error handler. 

After this middleware I put my custom nodejs error handler middleware with four parameters (err, req, res, next), obviously whatever it returns hit my custom error handler. I handled the error there. 

Hope this is helpful.

**Comment by karellodewijk** [comment]
The behavior was changed, caught me by surprise to. When the token is invalid it will now go to the error handler even if {credentialsRequired: false} is set. It used to be that it just continued as an unauthenticated user.

You can go back to the previous behavior by eating the error like so:

```
var ejwt = require('express-jwt');
app.use(ejwt({secret: config.app.secret, credentialsRequired: false}), function (err, req, res, next) {
  if (err.code === 'invalid_token') return next();
  return next(e);
});
```

**Comment by pie6k** [comment]
@karellodewijk solution seems to work, but it's weird to create custom error handlers while `credentialsRequired` is set to `false`.

**Comment by paulbuying** [comment]
@karellodewijk I think the `e` in `next(e)` should be `err`.

**Comment by iamchathu** [comment]
Any update on this?

**Comment by nolandg** [comment]
This is rather counter-intuitive behaviour. I would expect all failures of the token to be silent if `credentialsRequired: false` is set.

**Comment by rebolyte** [comment]
To work around this I ended up creating a separate middleware for my routes that needed to allow an expired token, and including the `ignoreExpiration` option that gets passed along to jsonwebtoken [here](https://github.com/auth0/express-jwt/blob/v6.1.0/lib/index.js#L103):

```js
expressJwt({
  secret: process.env.JWT_SECRET,
  credentialsRequired: false,
  ignoreExpiration: true
});
```
